version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8000:8000
    restart: always
    depends_on: 
      - llm
    networks:
      - poc-network

  app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on: 
      - api
    networks:
      - poc-network

  llm:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    # environment:
      # - OLLAMA_KEEP_ALIVE=24h
    networks:
      - poc-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  poc-network:
    external: false
